### ISSUE TITLE
Solution branch

### ISSUE THREAD

**Issue by binaryseed** [elixir-pdx/zee_pipes#3]
I played around with this one till I got a solution that I was happy with, could you create me a branch again @nathanaschbacher ?

**Comment by nathanaschbacher** [comment]
Sure, will do it now. It'll be called "vince"

I played around with this one till I got a solution that I was happy with,
could you create me a branch again @nathanaschbacher
https://github.com/nathanaschbacher ?

—
Reply to this email directly or view it on GitHub
https://github.com/elixir-pdx/zee_pipes/issues/3.
